name: Deploy Web Game

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          npm install
          npm run build
          git config --global user.email "mohamedfountir@gmail.com"
          git config --global user.name "mohamed"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN}}
          git commit -m "Deploying to main"
          git push --force origin main
